language: android
jdk:
  - oraclejdk8

sudo: required # disables container-based builds which have a maximum of 4GB of memory

os: linux
dist: trusty

android:
  components:
    # Base components 
    - tools # to get the new `repository-11.xml`
    - tools # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools   
    - build-tools-29.0.2

    # used sdk versions
    - android-29 # get the android sdk version to build the project
    - android-24 # get the android sdk version for the emulator

    # Get the latest version of additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

    # Specify the needed emulator
    - sys-img-armeabi-v7a-android-24

licenses:
  - 'android-sdk-license-.+'
  - '.+'

before_script:
  # Create and start the emulator
  - sdkmanager "system-images;android-24;google_apis;armeabi-v7a"
  - echo no | avdmanager -v create avd -f -n test -k "system-images;android-24;google_apis;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

  - android-wait-for-emulator

  # Turn off animations
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

  # Wake up
  - adb shell input keyevent 82 &
  - adb shell input keyevent 1 &

script:
  - ./gradlew test # Local unit test
  - ./gradlew connectedAndroidTest # Instrumented unit test
  - ./gradlew lint #maybe at some point
  #- ./gradlew clean test build